title: "aristide_mibo_portfolio"
logo:  https://aristidemibo.github.io/aristide_mibo_portfolio/main/img/amk.jpg
description: "portfolio aristide mibo data scientist, formation"
show_downloads: true
theme: jekyll-theme-modernist
lang: fr 
